//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Megrendelo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Megrendelo()
        {
            this.Megrendeles = new HashSet<Megrendeles>();
        }
    
        public int VasarloID { get; set; }
        public string Nev { get; set; }
        public string Cim { get; set; }
        public string Varos { get; set; }
        public string Iranyitoszam { get; set; }
        public string Telefonszam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Megrendeles> Megrendeles { get; set; }
    }
}
