//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClothShop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ruha
    {
        public int RuhaID { get; set; }
        public Nullable<int> Ar { get; set; }
        public string Tipus { get; set; }
        public string Anyag { get; set; }
        public Nullable<int> Meret { get; set; }
    }
}
